CREATE TABLE IF NOT EXISTS public.loan_approval_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP, updated_at TIMESTAMP,
  loan_id BIGINT NOT NULL REFERENCES public.loans(id),
  step_order INTEGER NOT NULL,
  required_role VARCHAR(50) NOT NULL,
  label VARCHAR(150) NOT NULL,
  approved_at TIMESTAMP,
  approved_by_member_id BIGINT,
  CONSTRAINT uk_loan_approval_step UNIQUE (loan_id, step_order)
);
CREATE TABLE IF NOT EXISTS public.loan_approval_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP, updated_at TIMESTAMP,
  loan_id BIGINT NOT NULL REFERENCES public.loans(id),
  step_order INTEGER,
  action VARCHAR(30) NOT NULL,
  actor_member_id BIGINT NOT NULL,
  reason TEXT,
  acted_at TIMESTAMP NOT NULL
);
